name: Deploy Hexo to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Generate static files
      run: npx hexo generate

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan breezev.cn >> ~/.ssh/known_hosts
        rsync -avz --delete ./public/ root@breezev.cn:/root/Projects/hexo-blog/breeze4u.github.io/public
